name: nutrovite
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.7.0
  google_generative_ai: ^0.4.6
  http: ^1.2.2
  google_fonts: ^6.2.1
  grouped_list: ^6.0.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  isar: ^3.1.0+1
  cloud_firestore: ^5.4.1
  path_provider: ^2.1.4
  firebase_storage: ^12.3.0
  uuid: ^4.5.0
  cached_network_image: ^3.4.1
  flutter_markdown: ^0.7.3+1
  shimmer: ^3.0.0
  isar_flutter_libs: ^3.1.0+1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# 🔹 Configuration for app launcher icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/output.png"
  # adaptive_icon_background: "#ffffff"
  # adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
