// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ5yYoxJ50p5_2gGl3Fn7L6i-kvh0QpqA',
    appId: '1:282065506247:android:30a09165109a2f55a1d3e2',
    messagingSenderId: '282065506247',
    projectId: 'nutrovite-7fa90',
    storageBucket: 'nutrovite-7fa90.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHyf1yOBxdI7UpYDi4HMbourd-Y7C2YN8',
    appId: '1:282065506247:web:a47b79ac8f9a8308a1d3e2',
    messagingSenderId: '282065506247',
    projectId: 'nutrovite-7fa90',
    authDomain: 'nutrovite-7fa90.firebaseapp.com',
    storageBucket: 'nutrovite-7fa90.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2t-mS37fkLKBd-KdD1DQiQy-hB0HfQRk',
    appId: '1:282065506247:ios:c408fae6bfb5ec42a1d3e2',
    messagingSenderId: '282065506247',
    projectId: 'nutrovite-7fa90',
    storageBucket: 'nutrovite-7fa90.appspot.com',
    iosBundleId: 'com.atx.nutrovite',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2t-mS37fkLKBd-KdD1DQiQy-hB0HfQRk',
    appId: '1:282065506247:ios:c408fae6bfb5ec42a1d3e2',
    messagingSenderId: '282065506247',
    projectId: 'nutrovite-7fa90',
    storageBucket: 'nutrovite-7fa90.appspot.com',
    iosBundleId: 'com.atx.nutrovite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHyf1yOBxdI7UpYDi4HMbourd-Y7C2YN8',
    appId: '1:282065506247:web:3c5d144954a20591a1d3e2',
    messagingSenderId: '282065506247',
    projectId: 'nutrovite-7fa90',
    authDomain: 'nutrovite-7fa90.firebaseapp.com',
    storageBucket: 'nutrovite-7fa90.appspot.com',
  );

}