on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Android Build & Store .aab and APK Files"
jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Step 5: Build APKs (split per ABI)
      - run: flutter build apk --debug --split-per-abi

      # Step 6: Upload Artifacts with v4
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release-files
          path: |
            build/app/outputs/apk/release/*.apk
